services:
    database:
        image: postgres:17.4
        container_name: echo-diary-database
        restart: always
        environment:
            POSTGRES_DB: echo_diary_database
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
