services:
    database:
        image: postgres:17.4
        container_name: echo-diary-database
        restart: always
        environment:
            POSTGRES_DB: echo_diary_database
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    mailhog:
        image: mailhog/mailhog:latest
        container_name: echo-diary-mailhog
        restart: always
        ports:
            - "1025:1025"
            - "8025:8025"

volumes:
    pgdata:
